// mockExaminations.ts
import { CoughDuration, LungFeature, KeySite } from '@/models/enums';
import { Examination } from '@/models/Examination';

export const mockExaminations: Examination[] = [
  {
    examinationId: "1004",
    patientId: "1004",
    userId: 500,
    date: new Date("2023-07-15T09:30:00Z"),
    patientName: "Jane Doe",
    patientAge: 34,
    patientLocalisation: "Urban Hospital",
    symptomWeightLoss: true,
    symptomNightSweats: false,
    symptomFever: true,
    symptomCough: true,
    symptomCoughDuration: CoughDuration.LONG,
    symptomHouseholdTBContact: true,
    images: [
      {
        imageId: "1",
        date: new Date("2023-07-15T09:45:00Z"),
        uri: "@/assets/images/mockUltrasound.png",
        keySite: KeySite.PAD,
        label: LungFeature.CONSOLIDATIONS,
      },
      {
        imageId: "2",
        date: new Date("2023-07-15T09:50:00Z"),
        uri: "@/assets/images/mockUltrasound.png",
        keySite: KeySite.QAID,
        label: LungFeature.SUBPLEURAL_CONSOLIDATIONS,
      },
      {
        imageId: "3",
        date: new Date("2023-07-15T09:45:00Z"),
        uri: "@/assets/images/mockUltrasound.png",
        keySite: KeySite.PAD,
        label: LungFeature.CONSOLIDATIONS,
      },
      {
        imageId: "4",
        date: new Date("2023-07-15T09:50:00Z"),
        uri: "@/assets/images/mockUltrasound.png",
        keySite: KeySite.QAID,
        label: LungFeature.SUBPLEURAL_CONSOLIDATIONS,
      },
      {
        imageId: "5",
        date: new Date("2023-07-15T09:45:00Z"),
        uri: "@/assets/images/mockUltrasound.png",
        keySite: KeySite.PAD,
        label: LungFeature.CONSOLIDATIONS,
      },
      {
        imageId: "6",
        date: new Date("2023-07-15T09:50:00Z"),
        uri: "@/assets/images/mockUltrasound.png",
        keySite: KeySite.QAID,
        label: LungFeature.SUBPLEURAL_CONSOLIDATIONS,
      },
      {
        imageId: "7",
        date: new Date("2023-07-15T09:45:00Z"),
        uri: "@/assets/images/mockUltrasound.png",
        keySite: KeySite.PAD,
        label: LungFeature.CONSOLIDATIONS,
      },
      {
        imageId: "8",
        date: new Date("2023-07-15T09:50:00Z"),
        uri: "@/assets/images/mockUltrasound.png",
        keySite: KeySite.QAID,
        label: LungFeature.SUBPLEURAL_CONSOLIDATIONS,
      },
    ],
    tbRisk: 78.2,
    ultrAiSign: 75.0,
    ultrAi: 73.5,
    recommendedAction: "Immediate referral for TB treatment is recommended.",
    note: "Patient shows signs consistent with TB infection. Further diagnostics are required.",
    pdfUrlSrc: "",
  },
  {
    examinationId: "1006",
    patientId: "1006",
    userId: 501,
    date: new Date("2023-06-20T11:15:00Z"),
    patientName: "John Smith",
    patientAge: 45,
    patientLocalisation: "City Clinic",
    symptomWeightLoss: false,
    symptomNightSweats: true,
    symptomFever: false,
    symptomCough: true,
    symptomCoughDuration: CoughDuration.MEDIUM,
    symptomHouseholdTBContact: false,
    images: [
      {
        imageId: "1",
        date: new Date("2023-06-20T11:30:00Z"),
        uri: "@/assets/images/mockUltrasound.png",
        keySite: KeySite.APXD,
        label: LungFeature.DRY_LUNG,
      },
      {
        imageId: "2",
        date: new Date("2023-07-15T09:50:00Z"),
        uri: "@/assets/images/mockUltrasound.png",
        keySite: KeySite.QAID,
        label: LungFeature.SUBPLEURAL_CONSOLIDATIONS,
      },
      {
        imageId: "3",
        date: new Date("2023-07-15T09:45:00Z"),
        uri: "@/assets/images/mockUltrasound.png",
        keySite: KeySite.PAD,
        label: LungFeature.CONSOLIDATIONS,
      },
      {
        imageId: "4",
        date: new Date("2023-07-15T09:50:00Z"),
        uri: "@/assets/images/mockUltrasound.png",
        keySite: KeySite.QAID,
        label: LungFeature.SUBPLEURAL_CONSOLIDATIONS,
      },
      {
        imageId: "5",
        date: new Date("2023-07-15T09:45:00Z"),
        uri: "@/assets/images/mockUltrasound.png",
        keySite: KeySite.PAD,
        label: LungFeature.CONSOLIDATIONS,
      },
    ],
    tbRisk: 35.0,
    ultrAiSign: 30.0,
    ultrAi: 32.5,
    recommendedAction: "Monitor symptoms and schedule follow-up.",
    note: "Patient has mild symptoms and low risk of TB.",
    pdfUrlSrc: "",
  },
  // Add more mock examinations as needed
];