import { Examination } from '@/models/Examination'; 

/**
 * This function generates the HTML content for the PDF report.
 * It uses the provided examination data to fill in the report.
 * @param exam The examination data to include in the report
 * @returns 
 */
export const getExamPdfHtml = (exam: Examination): string => {
  // Format the date
  const examDate = new Date(exam.date).toLocaleDateString();
  
  // Convert booleans to Yes/No
  const yesNo = (value: boolean) => (value ? 'Yes' : 'No');

  return `
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
          body {
            font-family: Arial, sans-serif;
            padding: 24px;
            line-height: 1.6;
            color: #333;
          }
          .header {
            text-align: center;
            margin-bottom: 24px;
          }
          .header h1 {
            font-size: 24px;
            margin: 0;
          }
          .section {
            margin-bottom: 20px;
          }
          .section-title {
            font-size: 18px;
            font-weight: bold;
            border-bottom: 1px solid #ccc;
            margin-bottom: 8px;
            padding-bottom: 4px;
          }
          .info-table {
            width: 100%;
            border-collapse: collapse;
          }
          .info-table td {
            padding: 4px 8px;
            vertical-align: top;
          }
          .info-table td.label {
            font-weight: bold;
            width: 35%;
            background-color: #f6f6f6;
          }
          .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 12px;
            color: #666;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Medical Examination Report</h1>
          <p>Hospital XYZ</p>
        </div>

        <div class="section">
          <div class="section-title">Patient Information</div>
          <table class="info-table">
            <tr>
              <td class="label">Patient Name:</td>
              <td>${exam.patientName}</td>
            </tr>
            <tr>
              <td class="label">Patient Age:</td>
              <td>${exam.patientAge}</td>
            </tr>
            <tr>
              <td class="label">Localisation:</td>
              <td>${exam.patientLocalisation}</td>
            </tr>
            <tr>
              <td class="label">Patient ID:</td>
              <td>${exam.patientId}</td>
            </tr>
            <tr>
              <td class="label">Examination Date:</td>
              <td>${examDate}</td>
            </tr>
          </table>
        </div>

        <div class="section">
          <div class="section-title">Symptoms</div>
          <table class="info-table">
            <tr>
              <td class="label">Weight Loss:</td>
              <td>${yesNo(exam.symptomWeightLoss)}</td>
            </tr>
            <tr>
              <td class="label">Night Sweats:</td>
              <td>${yesNo(exam.symptomNightSweats)}</td>
            </tr>
            <tr>
              <td class="label">Fever:</td>
              <td>${yesNo(exam.symptomFever)}</td>
            </tr>
            <tr>
              <td class="label">Cough:</td>
              <td>${yesNo(exam.symptomCough)}</td>
            </tr>
            <tr>
              <td class="label">Cough Duration:</td>
              <td>${exam.symptomCoughDuration}</td>
            </tr>
            <tr>
              <td class="label">Household TB Contact:</td>
              <td>${yesNo(exam.symptomHouseholdTBContact)}</td>
            </tr>
          </table>
        </div>

        <div class="section">
          <div class="section-title">Ultrasound Analysis</div>
          <table class="info-table">
            <tr>
              <td class="label">TB Risk:</td>
              <td>${exam.tbRisk.toFixed(1)}%</td>
            </tr>
            <tr>
              <td class="label">UltrAI Sign:</td>
              <td>${exam.ultrAiSign.toFixed(1)}%</td>
            </tr>
            <tr>
              <td class="label">UltrAI:</td>
              <td>${exam.ultrAi.toFixed(1)}%</td>
            </tr>
          </table>
        </div>

        <div class="section">
          <div class="section-title">Recommended Action</div>
          <p>${exam.recommendedAction}</p>
        </div>

        <div class="section">
          <div class="section-title">Additional Notes</div>
          <p>${exam.note}</p>
        </div>

        <div class="footer">
          <p>This PDF was generated by the AI-based Lung Ultrasound Analysis System.</p>
        </div>
      </body>
    </html>
  `;
};